### PR TITLE
Introducing feature/progressbar style

### PR DESCRIPTION
**Pull request by johannwagner**
Hey, 

we needed a custom style flag on the ProgressBar of react-toastify for applying a custom theme from material-ui. We thought, this would be a great addition for this package.

I also added documentation for this flag.

Let me know, what you think.

Best Regards, 
   Johann

### CODE REVIEW

**Comment by fkhadra** [comment]
Hey @johannwagner,

This is really nice, thank you ! Could you share a gif of what it looks like in your case? Just to satisfy my curiosity ^^.

**Comment by johannwagner** [comment]
screenshot from 2018-09-28 12-55-27

I can just share a picture with you with an applied theme from material-ui. Hope, this satisfies you.

**Comment by johannwagner** [comment]
And it is a variant of the primary color in our application.
screenshot from 2018-09-28 12-56-28

**Comment by fkhadra** [comment]
Neat 👌.

**Comment by johannwagner** [comment]
@fkhadra Is there a date for a merge into master?

**Pull request merged**
