### PR TITLE
Use variable defaults in SCSS

### PR DESCRIPTION
**Pull request by vikpe**
This enables customisation without touching the original source code.

**Example usage**
```javascript
@include 'my_custom_variables';
@include 'react-toastify/src/scss/main';
```
(reference: [Variable defaults](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#Variable_Defaults___default))

### CODE REVIEW

**Comment by andli** [comment]
Please merge this, would love to change color scheme this way.

**Comment by fkhadra** [comment]
@andli sure ! Sorry was quit busy. I'm on it.

**Comment by fkhadra** [comment]
@vikpe, @andli. It's live ! 😄 Thanks for the pull request. I also added a [doc](https://github.com/fkhadra/react-toastify#replace-default-sass-variable)

**Comment by vikpe** [comment]
Another suggestion on the same topic is to namespace (prefix) all variables, eg:

```scss
$rt-toast-width: 320px !default;
$rt-toast-background: #ffffff !default;
$rt-font-color: #999 !default;
$rt-font-size: 13px !default;
$rt-animation-duration: 0.75s !default;
```
This prevents collisions/unwanted behavior when importing variables from various vendors.

In addition; it increases the readability/findability as you can search for "`$rt-`" in your IDE to quickly find instances of react-toastify variables.

**Comment by fkhadra** [comment]
I made the [changes](https://github.com/fkhadra/react-toastify/pull/70). I publish when CI is done

**Comment by vikpe** [comment]
Awesome, thank you for this great repo/component!

**Comment by fkhadra** [comment]
Glad you like it ! The v2.2.0 is live

**Pull request merged**
