### PR TITLE
Issue#512 Specify the direction for swipe-to-close

### PR DESCRIPTION
**Pull request by denydavy**

### CODE REVIEW

**Comment by fkhadra** [comment]
Hello @denydavy,

First of all, thanks a lot for your collaboration! A really nice feature that you are adding there 💪.  May I ask you to rebase your branch onto the next branch?

I've removed `prop-types`, so this is something you can drop as well in your PR. 

I've already opened a draft PR for the next release, you can check the details here #554. I don't think that my changes will impact yours.

**Comment by denydavy** [comment]
> Hello @denydavy,
> 
> First of all, thanks a lot for your collaboration! A really nice feature that you are adding there 💪. May I ask you to rebase your branch onto the next branch?
> 
> I've removed `prop-types`, so this is something you can drop as well in your PR.
> 
> I've already opened a draft PR for the next release, you can check the details here #554. I don't think that my changes will impact yours.

Hello @fkhadra! Sure thing.

**Comment by denydavy** [comment]
Done & done. Could you please check whether everything is ok? 
P.S. I forgot to thank you for the very existence of this library in the first place, so thank you very much :)

**Comment by fkhadra** [comment]
It works like a charm. Really nice. I have one concern though. The `removal distance` feels a bit too short. I have the feeling that the notification fades out too soon. 

https://user-images.githubusercontent.com/5574267/103479648-7ddaea80-4dcf-11eb-9435-40fb374d7ba9.mov

I was thinking to multiply the `props.daraggablePercent` by `1.5` when the drag direction is `Y` and that the end-user didn't set the `daraggablePercent` on his own.


https://user-images.githubusercontent.com/5574267/103479826-9bf51a80-4dd0-11eb-8eb6-76e53090959e.mov

Let me know what you think about it :)

**Comment by denydavy** [comment]
> It works like a charm. Really nice. I have one concern though. The `removal distance` feels a bit too short. I have the feeling that the notification fades out too soon.
> 
>  dragy.mov 
> I was thinking to multiply the `props.daraggablePercent` by `1.5` when the drag direction is `Y` and that the end-user didn't set the `daraggablePercent` on his own.
> 
>  dragy15.mov 
> Let me know what you think about it :)

Hello @fkhadra ! It doesn't looks THAT different but I get what you mean :). There is way less distance to cover in Y axis so slowing the fade is a good idea.

**Comment by fkhadra** [comment]
I'll merge your changes in my branch. I'm planning to publish the new release this week. I'll keep you posted. Thanks for the contribution !

**Comment by denydavy** [comment]
> I'll merge your changes in my branch. I'm planning to publish the new release this week. I'll keep you posted. Thanks for the contribution !

Great! Thanks a lot!

**Pull request merged**
