### PR TITLE
Better redux example

### LINKED ISSUE #283: Redux example shows anti-pattern
In the redux-demo you create a side effect from the reducers:
```js
import { toast } from "react-toastify";

const initialState = {
  value: 0
};

function addReducer(state = initialState, action) {
  switch (action.type) {
    case "INCREMENT":
      toast.success("INCREMENT");
      return { ...state, value: state.value + 1 };
    case "DECREASE":
      toast.warn("DECREASE");
      return { ...state, value: state.value - 1 };
    default:
      return state;
  }
}

export default addReducer;
```
You should never do this, this is a total anti-pattern. I suggest triggering these side effects in a thunk (where you do not await the result, but still it is more transparent to create a side effect from a thunk than from a reducer). The current example will make people adopt this bad style.

### PR DESCRIPTION
**Pull request by Levino**
Fix #283.

Potentially you want to fork my codesandbox again under your own account and use this. I do not guarantuee that I will maintain it.

### CODE REVIEW

**Comment by Levino** [comment]
I guess this should be merged, no?

**Comment by Levino** [comment]
Then leave the issue open. It will be closed automatically when you merge this pull request.

**Comment by fkhadra** [comment]
Hello @Levino,

I forked the sandbox and putted you as commit author: https://github.com/fkhadra/react-toastify/pull/289/commits/a822cea8c88d4453e727ced3cb648f2668fd44da

**Comment by fkhadra** [comment]
You're welcome. Enjoy the rest of the weekend

**Pull request closed without merging**
