### PR TITLE
Add multiple container support (optional).

### PR DESCRIPTION
**Pull request by mudafar**
Hi @fkhadra,

We faced an issue similar to these mentioned here:
https://github.com/fkhadra/react-toastify/issues/134

I tried to fix the issue with no luck, so I ended up with this PR, in theory it pass all the test, and the contribution recommendation, nevertheless let me know what do you think and let me know if I need to add/modify anything :)

Basically I included an explanation about the logic and how to use it in the readme.

The idea is to ensure there is no duplication of any toast inside and outside of a deployed component which use `react-toastify` internally. (parent and child using the library).

### CODE REVIEW

**Comment by fkhadra** [comment]
Hey @mudafar,

This look good 👌but may I ask you to write the corresponding test. If you don't know how I can point you to the right direction.

Thanks a lot for the PR BTW !

**Comment by mudafar** [comment]
Hey @fkhadra,

Sure I'll add the corresponding test and let you know!

I'm glad that you liked the PR.

**Comment by mudafar** [comment]
Hi @fkhadra ,

Test added, please when you've time check them and let me know.

I faced something strange, and it turns out that any test that create a toast after this one:

```js
  it("Should throw an error if can't render a toast", () => {
    expect(() => {
      mount(<ToastContainer />);
      toast(false);
      jest.runAllTimers();
    }).toThrow(/The element you provided cannot be rendered/);
  });
```

Will keep throwing the same boolean type error, I couldn't find a solution for that!

Please let me know what you think about the tests.


Thanks!

**Comment by fkhadra** [comment]
Hey @mudafar,

I'll check ASAP don't worry.

**Comment by mudafar** [comment]
Hi @fkhadra ,

Please let me know if the tests are ok, and/or I need to add anything else.

Thanks!

**Comment by mudafar** [comment]
Hey @fkhadra ,

Thanks for your detailed review, and don't worry about the test thing :)


About the remarks:

1. You're right, it's better to unify to `containerId` in both cases.
2. I thought about it too, IMHO the idea behind `enableMultiContainer ` is to:
  2.1. Make it explicit (as you already mentioned). 
  2.2. Prevent activating the multiple container unintentionally.
  2.3. Prevent a complex logic for the end user, e.g: `if you add containerId, this also will activate multiple container etc...`, as per the _Single Responsibility Principle_
  2.4. Keep it optional as possible (it's not a common use-case).
  
I'll change the `containerId` and push the changes, let me know what do you think about the second remark.


Great review 👍

**Comment by fkhadra** [comment]
@mudafar I think we are ready to release it now 😁. Thank you

**Comment by mudafar** [comment]
Hi @fkhadra ,

Great news, please let me know when it's released, I need to use this feature.

Thank you in advance!

**Comment by fkhadra** [comment]
hey @mudafar, it's published to npm 😎

**Comment by mudafar** [comment]
Great, thank you @fkhadra !

**Pull request merged**
