### PR TITLE
Issue#483

### PR DESCRIPTION
**Pull request by AmooHashem**
As was mentioned in issue comments, I search for a race condition and check every thing that thought might have effect on race.
I just change a setTimeout() duration to zero and it works (at least in playground) and also, it pass all the tests.

### CODE REVIEW

**Comment by fkhadra** [comment]
Hey @AmooHashem, thanks for your contribution.

Unfortunately, this change will prevent the collapse animation to work when you have many notifications displayed at the same time.

https://user-images.githubusercontent.com/5574267/102722858-56cae600-4304-11eb-81d0-c0b96c3dd49a.mov

**Comment by fkhadra** [comment]
@AmooHashem, one solution would be maybe to do as follow

```js
export function collapseToast(
  node: HTMLElement,
  done: () => void,
  duration = DEFAULT.COLLAPSE_DURATION
) {
  const height = node.scrollHeight;
  const style = node.style;
  
  // rely  on transitionend instead of timeout 
  node.addEventListener('transitionend', () => done());
  
  requestAnimationFrame(() => {
    style.minHeight = 'initial';
    style.height = height + 'px';
    style.transition = `all ${duration}ms`;

    requestAnimationFrame(() => {
      style.height = '0';
      style.padding = '0';
      style.margin = '0';
      // remove setTimeout
      // setTimeout(() => done(), duration as number);
    });
  });
}

```

**Comment by AmooHashem** [comment]
> @AmooHashem, one solution would be maybe to do as follow
> 
> ```js
> export function collapseToast(
>   node: HTMLElement,
>   done: () => void,
>   duration = DEFAULT.COLLAPSE_DURATION
> ) {
>   const height = node.scrollHeight;
>   const style = node.style;
>   
>   // rely  on transitionend instead of timeout 
>   node.addEventListener('transitionend', () => done());
>   
>   requestAnimationFrame(() => {
>     style.minHeight = 'initial';
>     style.height = height + 'px';
>     style.transition = `all ${duration}ms`;
> 
>     requestAnimationFrame(() => {
>       style.height = '0';
>       style.padding = '0';
>       style.margin = '0';
>       // remove setTimeout
>       // setTimeout(() => done(), duration as number);
>     });
>   });
> }
> ```

but in this case, it will fail some tests.

**Comment by fkhadra** [comment]
I'm currently working on the removal of react-transition-group #514 . I have a working solution but I have to adapt a bunch of tests right now. There is an impact on this part of the code. I'll try to push my code when it's stable

**Comment by fkhadra** [comment]
I found the root cause. I'll open a PR soon with the fix

**Pull request closed without merging**
