### PR TITLE
use mjs extensions for es modules

### LINKED ISSUE #766: React Toastify not recognized as an ES module
**Do you want to request a *feature* or report a *bug*?**

I think this is a bug with the bundle.

**What is the current behavior?**

React Toastify is not recognized as an ES module. The build of an next application with react toastify will fail with the following error. 

```
SyntaxError: Named export 'ToastContainer' not found. The requested module 'react-toastify' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react-toastify';
```

**What is the expected behavior?**

It should not fail with this error and just load the ES module.

**Demo-Repo**

https://github.com/openpatch/patches-nextjs-starter/tree/dcd30554da8c1cd393a8c15be4f2d4c6ae8777c8

**Solution**

I think the filename is not correct. Since this package does not specify, that it is a module via the type field in the package json. The `js` will interpret as a CommonJS module. See here: https://github.com/developit/microbundle#usage-with-typemodule-in-packagejson. 

There are two solutions to the problem:

1. Add type: "module" to the package.json and replace the `js` extension with `cjs` for the CommonJS output.
2. Replace the `js` extension with `mjs` for the ES module output `react-toastify.esm.js`.

### PR DESCRIPTION
**Pull request by mikebarkmin**
This pull request fixes #766

### CODE REVIEW

**Comment by consegrado** [comment]
@fkhadra, I really need this PR, without it I can't build my project using [vitejs](https://vitejs.dev/), thanks

**Comment by fkhadra** [comment]
@consegrado could you test this PR with multiple builders? That would be very helpful
- vitejs
- nextjs
- CRA

**Comment by consegrado** [comment]
@fkhadra Sorry for the long answer, locally checked on new cra, nexjs, vitejs + react projects with this PR, no build problems, everything is OK

**Review by fkhadra — APPROVED** [review]

**Comment by fkhadra** [comment]
@consegrado @mikebarkmin. Thanks for testing it. I've published a new version

**Pull request merged**
