### PR TITLE
Add onClick to toast and ToastContainer

### PR DESCRIPTION
**Pull request by alexluong**
#248 #160

Now, user can do something like:

```
toast("Some notification", {
  onClick: e => {
    // Do something
  }
})
```

Or

```
<ToastContainer
  ....
  onClick={e => {
    // Default onClick
    // Do something
  }}
/>
```

Please let me know if you think the API seems good. Hope this is helpful.

### CODE REVIEW

**Comment by rtman** [comment]
@fkhadra whats the status of this? Any chance this can get merged? I would also like an onClick to do an action when the user clicks the toast.

**Comment by GLuchtenberg** [comment]
@rtman did you solve your problem? I need to implement an onClick too :sob:

**Comment by fkhadra** [comment]
Hello guys,

TBH I forgot why I put the PR "on hold" I'll review it ASAP.

**Comment by GLuchtenberg** [comment]
I need to fire a toast inside redux-saga with a message coming from intl

Use a component inside redux saga is kind of weird... I did it but I really would appreciate a better way to solve this kind of situation

**Comment by lhkraus** [comment]
Any updates about this? This feature is so good.

**Comment by renanperalta** [comment]
Any updates about this?

**Comment by JulianoGTZ** [comment]
I need this merge. I will be fired if I have to make another workaround because of this error.

**Comment by ramospedro** [comment]
> Hello guys,
> 
> TBH I forgot why I put the PR "on hold" I'll review it ASAP.
> 
> > Edit
> > If you do as follow, this does not solve your use case ?
> 
> ```js
> toast(<Msg onClick={fn}/>)
> ```

It looks like tests are missing. Maybe this would be the reason?
Btw, I'm very interested in this feature. Let me know if any help is needed : )

**Comment by LeonardoPrange** [comment]
Any updates about this?

**Comment by rafaelcaviquioli** [comment]
Please! I need these PR, it wil turn me more happy!

**Comment by emwp** [comment]
Any updates about this? This feature is so good.

**Comment by fkhadra** [comment]
Hey everyone,

I'll put the focus on it.

**Comment by LeonardoPrange** [comment]
@fkhadra thanks <3

**Comment by fkhadra** [comment]
This will be released on monday.

**Pull request merged**
